name: 'Transfer Private GitHub Issues into Google Sheets'
description: 'Do you want to import your Issues info into Google Sheets?'
branding:
  icon: 'bar-chart-2'  
  color: 'green'
inputs:
  google-api-service-account-credentials:
    description: "Google API Service Account credentials JSON"
    required: true
  document-id:
    description: "Google Sheets document ID"
    required: true
  sheet-name:
    description: "Google Sheets list name to insert Issues data"
    required: true
  github-access-token:
    description: "GitHUb Personal Access Token"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
